---
name: Preflight

on:
  - pull_request
  - push

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: macOS-latest
    steps:
      - name: xcode version
        run: xcodebuild -version -sdk
