---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types: 
      - completed
      - requested

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-18.04
    steps:
      - run: echo "$GITHUB_CONTEXT"
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: actions/checkout@v2
      - name: Show branches
        run: git branch
      - name: Debug
        shell: bash
        run: env
