---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types: 
      - completed
      - requested

jobs:
  pipeline-component:
    name: Test Step
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        shell: bash
        run: env
